# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_arrival_rate = QtWidgets.QLabel(self.centralwidget)
        self.label_arrival_rate.setGeometry(QtCore.QRect(90, 30, 141, 18))
        self.label_arrival_rate.setObjectName("label_arrival_rate")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(460, 70, 80, 26))
        self.btn_clear.setObjectName("btn_clear")
        self.lineEdit_service_rate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_service_rate.setGeometry(QtCore.QRect(270, 60, 111, 21))
        self.lineEdit_service_rate.setObjectName("lineEdit_service_rate")
        self.lineEdit_num_servers = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_servers.setGeometry(QtCore.QRect(270, 91, 113, 21))
        self.lineEdit_num_servers.setObjectName("lineEdit_num_servers")
        self.btn_simulate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_simulate.setGeometry(QtCore.QRect(460, 30, 80, 26))
        self.btn_simulate.setObjectName("btn_simulate")
        self.label_num_servers = QtWidgets.QLabel(self.centralwidget)
        self.label_num_servers.setGeometry(QtCore.QRect(90, 90, 141, 18))
        self.label_num_servers.setObjectName("label_num_servers")
        self.label_service_rate = QtWidgets.QLabel(self.centralwidget)
        self.label_service_rate.setGeometry(QtCore.QRect(90, 60, 141, 18))
        self.label_service_rate.setObjectName("label_service_rate")
        self.lineEdit_arrival_rate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_arrival_rate.setGeometry(QtCore.QRect(270, 30, 113, 21))
        self.lineEdit_arrival_rate.setObjectName("lineEdit_arrival_rate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        self.btnMenu_archivo = QtWidgets.QMenu(self.menubar)
        self.btnMenu_archivo.setObjectName("btnMenu_archivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.btnMenu_archivo.addAction(self.actionSalir)
        self.menubar.addAction(self.btnMenu_archivo.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_clear.clicked.connect(self.lineEdit_service_rate.clear) # type: ignore
        self.btn_clear.clicked.connect(self.lineEdit_arrival_rate.clear) # type: ignore
        self.btn_clear.clicked.connect(self.lineEdit_num_servers.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_arrival_rate, self.lineEdit_service_rate)
        MainWindow.setTabOrder(self.lineEdit_service_rate, self.lineEdit_num_servers)
        MainWindow.setTabOrder(self.lineEdit_num_servers, self.btn_simulate)
        MainWindow.setTabOrder(self.btn_simulate, self.btn_clear)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de colas"))
        self.label_arrival_rate.setText(_translate("MainWindow", "Tasa de arribos:"))
        self.btn_clear.setText(_translate("MainWindow", "Limpiar"))
        self.btn_simulate.setText(_translate("MainWindow", "Simular"))
        self.label_num_servers.setText(_translate("MainWindow", "Número de servidores:"))
        self.label_service_rate.setText(_translate("MainWindow", "Tasa de servicio:"))
        self.btnMenu_archivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
