# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 871, 211))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mms = QtWidgets.QWidget()
        self.tab_mms.setObjectName("tab_mms")
        self.lineEdit_arrival_rate = QtWidgets.QLineEdit(self.tab_mms)
        self.lineEdit_arrival_rate.setGeometry(QtCore.QRect(260, 30, 113, 21))
        self.lineEdit_arrival_rate.setObjectName("lineEdit_arrival_rate")
        self.lineEdit_num_servers = QtWidgets.QLineEdit(self.tab_mms)
        self.lineEdit_num_servers.setGeometry(QtCore.QRect(260, 91, 113, 21))
        self.lineEdit_num_servers.setObjectName("lineEdit_num_servers")
        self.btn_simulate = QtWidgets.QPushButton(self.tab_mms)
        self.btn_simulate.setGeometry(QtCore.QRect(450, 30, 80, 26))
        self.btn_simulate.setObjectName("btn_simulate")
        self.label_service_rate = QtWidgets.QLabel(self.tab_mms)
        self.label_service_rate.setGeometry(QtCore.QRect(80, 60, 141, 18))
        self.label_service_rate.setObjectName("label_service_rate")
        self.btn_clear = QtWidgets.QPushButton(self.tab_mms)
        self.btn_clear.setGeometry(QtCore.QRect(450, 70, 80, 26))
        self.btn_clear.setObjectName("btn_clear")
        self.lineEdit_service_rate = QtWidgets.QLineEdit(self.tab_mms)
        self.lineEdit_service_rate.setGeometry(QtCore.QRect(260, 60, 111, 21))
        self.lineEdit_service_rate.setObjectName("lineEdit_service_rate")
        self.label_num_servers = QtWidgets.QLabel(self.tab_mms)
        self.label_num_servers.setGeometry(QtCore.QRect(80, 90, 141, 18))
        self.label_num_servers.setObjectName("label_num_servers")
        self.label_arrival_rate = QtWidgets.QLabel(self.tab_mms)
        self.label_arrival_rate.setGeometry(QtCore.QRect(80, 30, 141, 18))
        self.label_arrival_rate.setObjectName("label_arrival_rate")
        self.progressBar_mms = QtWidgets.QProgressBar(self.tab_mms)
        self.progressBar_mms.setGeometry(QtCore.QRect(740, 150, 118, 23))
        self.progressBar_mms.setProperty("value", 24)
        self.progressBar_mms.setObjectName("progressBar_mms")
        self.tabWidget.addTab(self.tab_mms, "")
        self.tab_mm1 = QtWidgets.QWidget()
        self.tab_mm1.setObjectName("tab_mm1")
        self.tabWidget.addTab(self.tab_mm1, "")
        self.frame_results_mms = QtWidgets.QFrame(self.centralwidget)
        self.frame_results_mms.setEnabled(False)
        self.frame_results_mms.setGeometry(QtCore.QRect(-1, 209, 871, 321))
        self.frame_results_mms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_results_mms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_results_mms.setObjectName("frame_results_mms")
        self.list_results_mms = QtWidgets.QListWidget(self.frame_results_mms)
        self.list_results_mms.setGeometry(QtCore.QRect(10, 10, 641, 301))
        self.list_results_mms.setStyleSheet("font-size: 20px;")
        self.list_results_mms.setItemAlignment(QtCore.Qt.AlignLeading)
        self.list_results_mms.setObjectName("list_results_mms")
        self.label = QtWidgets.QLabel(self.frame_results_mms)
        self.label.setGeometry(QtCore.QRect(670, 20, 191, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 30))
        self.menubar.setObjectName("menubar")
        self.btnMenu_archivo = QtWidgets.QMenu(self.menubar)
        self.btnMenu_archivo.setObjectName("btnMenu_archivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.btnMenu_archivo.addAction(self.actionSalir)
        self.menubar.addAction(self.btnMenu_archivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_clear.clicked.connect(self.lineEdit_service_rate.clear) # type: ignore
        self.btn_clear.clicked.connect(self.lineEdit_arrival_rate.clear) # type: ignore
        self.btn_clear.clicked.connect(self.lineEdit_num_servers.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_arrival_rate, self.lineEdit_service_rate)
        MainWindow.setTabOrder(self.lineEdit_service_rate, self.lineEdit_num_servers)
        MainWindow.setTabOrder(self.lineEdit_num_servers, self.btn_simulate)
        MainWindow.setTabOrder(self.btn_simulate, self.btn_clear)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de colas"))
        self.btn_simulate.setText(_translate("MainWindow", "Simular"))
        self.label_service_rate.setText(_translate("MainWindow", "Tasa de servicio:"))
        self.btn_clear.setText(_translate("MainWindow", "Limpiar"))
        self.label_num_servers.setText(_translate("MainWindow", "Número de servidores:"))
        self.label_arrival_rate.setText(_translate("MainWindow", "Tasa de arribos:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mms), _translate("MainWindow", "M/M/s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mm1), _translate("MainWindow", "M/M/1"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.btnMenu_archivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
